runtime: python
env: flex
entrypoint: gunicorn "lsailor:create_app()"

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

env_variables:
  DATABASE_URL: "<specify database details>"

handlers:
- url: /
  secure: always
  script: auto